logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    role: USER,ADMIN
  ignored:
  - "*.bundle.*"
spring:
  redis:
    host: 192.168.99.100
    port: 6379
  session:
    store-type: redis
server:
  port: 8082
