security:
  user:
    password: password
  ignored:
  - "*.bundle.*"
spring:
  redis:
    host: 192.168.99.100
    port: 6379
  session:
    store-type: redis
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
